### ISSUE TITLE
Minecraft 1.20.1

### ISSUE THREAD

**Issue by Oggzw** [NyanMC/StableSocketing#1]
Hi,

Do you think you could make a version of this for 1.20.1?

Really sad that the original mod seems to have been abandoned but your fix is really nice!

**Comment by NyanMC** [comment]
I'll look into it. Best case scenario the same fix works for both versions and I can just remove or increase the version range listed in the mods.toml file, worst case I can make a separate jar which fixes the 1.20.1 version.

**Comment by NyanMC** [comment]
It appears to not be the best case scenario, but it isn't the worst either. Not much changed between the two versions, and there were only two significant changes which make the existing 1.19.2 version unable to work on 1.20.1. The fix shouldn't take long, unless more issues are found.

**Comment by NyanMC** [comment]
Just added a 1.20.1 file to [the existing 1.0.0 github release](https://github.com/NyanMC/StableSocketing/releases/tag/1.0.0) that should hopefully fix the issue on that version. It is really hard to test, and therefore I just assumed the same fix works on both versions. If you encounter any crashes still, reopen this issue.
